/**
 * THE DECK CANNOT DESCRIBE AN ORDER THE CODE DOES NOT HAVE (E19/S1).
 *
 * WHAT WENT WRONG. Nine deck sections state, in prose, the order their
 * sentences reach the screen. Every one was hand-written in
 * `scripts/export-copy-deck.mjs` and nothing bound it to the assembler. Reorder
 * `spreadLines` and the deck describes the old order; no test fails. The deck
 * is about to go to a writer with the repository CLOSED (RT-S3 a), so that
 * prose is the only thing they have.
 *
 * WHY THIS FILE IS NOT A TAUTOLOGY, WHICH IS THE FAIR OBJECTION. The assembler
 * now runs off the spec, so "the spec reproduces the assembler" would be a test
 * of nothing. Two things here are not:
 *
 *   (a) THE DECK ON DISK carries the sentence composed from the spec, character
 *       for character. Reorder the parts without regenerating and this fails.
 *       That is the drift the single source cannot prevent on its own, because
 *       the deck is a committed artefact read by someone with no repository.
 *
 *   (b) `always` IS CHECKED AGAINST THE WHOLE FIXTURE CORPUS. A part declared
 *       to fire every time must fire in every case; a part declared conditional
 *       must fire in at least one and be absent in at least one. This is the
 *       claim that used to be pure assertion, and it is the historical failure
 *       mode: the description going false while the order stayed put.
 *
 * THE ROSTER IS DERIVED, NOT TYPED. The corpus list below is checked to cover
 * exactly `EMISSION_SPECS`, so converting a surface in a later slice and
 * forgetting to exercise it fails here rather than passing quietly.
 */
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { computeSpreadResult } from "@/engine/spread";
import { computeDelicacyResult } from "@/engine/delicacy";
import { BIAS_EMISSION, creatorLines as biasCreatorLines } from "./bias";
import { DELICACY_EMISSION, creatorLines as delicacyCreatorLines } from "./delicacy";
import { THRESHOLD_EMISSION, creatorLines as thresholdCreatorLines } from "./threshold";
import { thresholdClaim } from "@/engine/evidence";
import { EMISSION_SPECS } from "./emission-registry";
import { emit, orderLine, type EmissionSpec } from "./emission";
import { SPREAD_EMISSION, spreadLines } from "./spread";
import { biasResults, delicacyResults, spreadCases, spreadRatings, thresholdSessions } from "./fixtures";

/** Files a writer is handed. Both are generated by one command; both must agree. */
const DECKS = ["docs/copy-deck-vocabulary.md", "docs/copy-deck.md"];

/**
 * One surface's spec beside every input the fixtures can drive it with.
 * `unknown` at the boundary and typed at each site, because the surfaces take
 * unrelated inputs and a shared type would be a lie about all but one.
 */
interface Corpus {
  readonly key: string;
  readonly spec: EmissionSpec<never>;
  readonly run: () => string[][];
  readonly firedPerCase: () => ReadonlyArray<ReadonlySet<string>>;
  /** The spec's output beside the assembler the product actually calls. */
  readonly agreement: () => ReadonlyArray<[string[], string[]]>;
}

function corpusFor<T>(
  key: string,
  spec: EmissionSpec<T>,
  inputs: () => T[],
  assembler: (input: T) => string[],
): Corpus {
  return {
    key,
    spec: spec as unknown as EmissionSpec<never>,
    agreement: () => inputs().map((input) => [assembler(input), emit(spec, input)]),
    run: () => inputs().map((input) => emit(spec, input)),
    firedPerCase: () =>
      inputs().map((input) => {
        const fired = new Set<string>();
        for (const part of spec.parts) {
          if (part.produce(input).length > 0) fired.add(part.id);
        }
        return fired;
      }),
  };
}

const spreadResults = () =>
  Object.values(spreadCases()).map((c) => computeSpreadResult(spreadRatings(c.ratings), c.recognised));

/** Only readable sessions reach the copy layer; the claim gate is upstream of it. */
const thresholdSays = () =>
  thresholdSessions()
    .map((session) => thresholdClaim(session))
    .filter((claim) => claim.ok)
    .map((claim) => claim.value);

const CORPUS: Corpus[] = [
  corpusFor("threshold", THRESHOLD_EMISSION, thresholdSays, thresholdCreatorLines),
  corpusFor("delicacy", DELICACY_EMISSION, () => Object.values(delicacyResults()), delicacyCreatorLines),
  corpusFor("bias", BIAS_EMISSION, () => Object.values(biasResults()), biasCreatorLines),
  corpusFor("spread", SPREAD_EMISSION, spreadResults, spreadLines),
];

describe("declared emission order", () => {
  it("exercises exactly the surfaces that declare a spec", () => {
    expect(CORPUS.map((c) => c.key).sort()).toEqual(Object.keys(EMISSION_SPECS).sort());
  });

  /*
   * `in` IS OPTIONAL IN THE TYPE AND REQUIRED IN PRACTICE, which is a judgment
   * call better made once than per surface. It exists because three assemblers
   * are all called `creatorLines`; leaving it off the ones whose names happen
   * to be unique asks a writer to know which names are unique, and they cannot
   * open the repository to find out.
   */
  it("tells a writer which file every block lives in", () => {
    for (const [key, spec] of Object.entries(EMISSION_SPECS)) {
      expect(spec.in, `${key} does not say which module its assembler lives in`).toBeTruthy();
    }
  });

  it("has a corpus and a spec worth checking, so nothing below passes vacuously", () => {
    for (const entry of CORPUS) {
      expect(entry.spec.parts.length, `${entry.key} declares fewer than two parts`).toBeGreaterThan(1);
      expect(entry.run().length, `${entry.key} has fewer than three fixture cases`).toBeGreaterThan(2);
    }
  });

  /**
   * (a) The committed deck carries the composed sentence. This is the guard
   * that bites when somebody reorders the parts and does not regenerate.
   */
  it("prints the declared order in every deck a writer is handed, under its own heading", () => {
    /*
     * ANCHORED TO THE LABEL, NOT SEARCHED FOR ANYWHERE IN THE FILE. A bare
     * substring match passes if the sentence turns up inside a code fence, in a
     * preamble, or — worse — under a DIFFERENT surface's heading, which is a
     * deck telling a writer the wrong thing while this test stays green.
     * Requiring it to OPEN an adjacency paragraph, exactly once, rules out all
     * three.
     */
    const LABEL = "**What renders with it, in order.** ";
    for (const [key, spec] of Object.entries(EMISSION_SPECS)) {
      const anchored = LABEL + orderLine(spec);
      for (const file of DECKS) {
        const hits = readFileSync(file, "utf8").split(anchored).length - 1;
        expect(
          hits,
          `${file} does not open exactly one adjacency paragraph with ${key}'s declared order ` +
            `(found ${hits}) — run node scripts/export-copy-decks.mjs. A deck describing an order ` +
            `the code does not have is what this mechanism exists to prevent: ${anchored}`,
        ).toBe(1);
      }
    }
  });

  /**
   * THE COMPOSER ITSELF, CHECKED DIRECTLY — the one thing a single source
   * cannot check about itself. Every other test here compares two views of the
   * same array, so if `orderLine` quietly stopped emitting the condition
   * clause, both views would move together and all of them would stay green
   * while the deck lost the half a writer needs most.
   */
  it("composes order and condition as separate, readable claims", () => {
    const sentence = orderLine({
      fn: "demoLines",
      parts: [
        { id: "a", says: "the first thing", always: true },
        { id: "b", says: "the second thing", always: false, when: "only when there is one" },
        { id: "c", says: "the third thing", always: true },
      ],
    });
    expect(sentence).toBe(
      "`demoLines` emits, in this order: (1) the first thing; (2) the second thing; " +
        "(3) the third thing. (1) and (3) render every time; (2) renders only when there is one.",
    );

    const allAlways = orderLine({
      fn: "demoLines",
      parts: [
        { id: "a", says: "the first thing", always: true },
        { id: "b", says: "the second thing", always: true },
      ],
    });
    expect(allAlways).toContain("All of them render every time.");
    expect(allAlways, "an unconditional block should not list conditions part by part").not.toContain(
      "(1) and (2) render",
    );
  });

  /**
   * (b) The one hand-written claim that a machine can check. `says` and `when`
   * stay prose and can still rot; `always` cannot.
   */
  it("keeps every `always` claim true across the whole fixture corpus", () => {
    for (const entry of CORPUS) {
      const cases = entry.firedPerCase();
      for (const part of entry.spec.parts) {
        const fired = cases.filter((c) => c.has(part.id)).length;
        if (part.always) {
          expect(
            fired,
            `${entry.key}/${part.id} is declared to render every time and did not on ` +
              `${cases.length - fired} of ${cases.length} fixture cases`,
          ).toBe(cases.length);
        } else {
          expect(
            fired,
            `${entry.key}/${part.id} is declared conditional ("${part.when}") but never renders`,
          ).toBeGreaterThan(0);
          expect(
            fired,
            `${entry.key}/${part.id} is declared conditional ("${part.when}") but renders on every ` +
              `case, so the deck understates what a reader always sees`,
          ).toBeLessThan(cases.length);
        }
      }
    }
  });

  /**
   * THE ASSEMBLER IS THE SPEC, and this pins that rather than assuming it. If
   * someone reintroduces a hand-assembled body beside the spec, the two stop
   * agreeing here before the deck starts lying.
   */
  it("is the function the product calls, not a description beside it", () => {
    /*
     * EVERY CONVERTED SURFACE, NOT JUST THE FIRST ONE (E19/S2). This checked
     * spread alone while three more assemblers were converted around it, so a
     * hand-assembled body left beside a spec would have gone unnoticed on any
     * of the other three — the exact drift the mechanism exists to remove.
     */
    for (const entry of CORPUS) {
      for (const [shipped, declared] of entry.agreement()) {
        expect(shipped, `${entry.key} does not assemble from its own spec`).toEqual(declared);
      }
    }
  });

  /**
   * THE PREMISE UNDER `delicacy/naming`'s `always: true`, CHECKED RATHER THAN
   * ASSUMED.
   *
   * `namingLine` returns null when `delicacyClaim` refuses, and it refuses only
   * on `nTrials === 0`. That state is unreachable because the engine throws on
   * an empty item list — so the part renders every time, and the corpus agrees.
   * But the corpus agrees for the weaker reason that no fixture builds one. If
   * the throw ever became a return, `always: true` would silently go false and
   * nothing else here would notice, because a fixture cannot exercise a state
   * its constructor refuses to build. This pins the throw instead.
   */
  it("rests `delicacy/naming` on a guarantee the engine actually makes", () => {
    expect(() => computeDelicacyResult("premise-check", [], {})).toThrow();
  });

  /**
   * A spec for a surface the deck has no section for would compose a sentence
   * nothing prints. Derived from the exporter's own keys, scanned as text for
   * the reason `deck-coverage.test.ts` gives: importing the exporter runs it.
   */
  it("declares specs only for surfaces the deck actually has a section for", () => {
    const source = readFileSync("scripts/export-copy-deck.mjs", "utf8");
    const keys = source.split('key: "').slice(1).map((part) => part.split('"')[0]);
    expect(keys.length).toBeGreaterThan(7);
    const strangers = Object.keys(EMISSION_SPECS).filter((k) => !keys.includes(k));
    expect(strangers, "these surfaces declare an emission order no deck section prints:").toEqual([]);
  });
});
