/**
 * EVERY SENTENCE THE VOCABULARY LAYER CAN EMIT (E8/S9).
 *
 * WHY A FIXTURE MODULE AND NOT A LIST. The four vocabulary modules branch on
 * band shape, on outcome kind, on verdict, on whether a family was measured,
 * and on how many instruments have run. Hand-listing the reachable sentences
 * would freeze whatever set I happened to think of; a branch nobody exercised
 * is exactly where an off-voice line survives, which is the argument
 * `staircaseCopyFixtures` already makes one directory over.
 *
 * So these are generated by driving the real engines across placements that
 * reach every branch, and the enumeration is asserted — `vocabulary.test.ts`
 * fails if a shape stops being covered.
 *
 * INTENSITY. Everything here is "pointed": these paragraphs sit beside a
 * number rather than carrying one themselves, and several are refusals, which
 * the "full" tier's datum rule would wrongly demand a figure from.
 */
import type { VoiceString } from "../voice";
import { creatorLines as thresholdLines } from "./threshold";
import { creatorLines as delicacyLines } from "./delicacy";
import { creatorLines as biasLines } from "./bias";
import { acrossLines, thresholdRoster, type AcrossInput } from "./across";
import { brierNote, expertStrings } from "./expert";
import { thresholdClaim } from "@/engine/evidence";
import { replicationCheck } from "@/engine/replication";
import type { ReplicationCheck } from "@/engine/replication";
import type { DegradationFamily } from "@/engine/delicacy";
import { DELICACY_INSTRUMENT_ID, MEASURED_TRIALS } from "@/content/delicacy/items";
import { computeDelicacyResult, type DelicacyResponses } from "@/engine/delicacy";
import { BIAS_CLIPS, BIAS_INSTRUMENT_ID } from "@/content/bias/items";
import { BIAS_SCALE_MAX, BIAS_SCALE_MIN, computeBiasResult } from "@/engine/bias";
import {
  answer,
  axisFor,
  isFinished,
  nextTrial,
  sessionResult,
  startSession,
  type StaircaseResult,
} from "@/engine/staircase-session";
import { eligibleSources } from "@/engine/staircase-pool";
import { observer, pCorrect, rng } from "@/analytics/observer";

/** A listener placed at `place` along the family's own ladder. See replication.test.ts. */
function session(family: string, place: number, seed: number, sourceId?: string): StaircaseResult {
  const mags = axisFor(family, sourceId).magnitudes;
  const lo = Math.log(mags[0] / 4);
  const hi = Math.log(mags[mags.length - 1] * 4);
  const o = observer(Math.exp(lo + (hi - lo) * place), 0.35, 0.02);
  let s = startSession(family, seed, sourceId);
  const rand = rng(seed ^ 0x5bf03635);
  while (!isFinished(s)) {
    const t = nextTrial(s);
    s = answer(s, rand() < pCorrect(s.axis.magnitudes[t.levelIndex], o));
  }
  return sessionResult(s);
}

/** Every threshold session the fixtures draw on — all ladders, all placements. */
export function thresholdSessions(): StaircaseResult[] {
  const ladders: Array<[string, string | undefined]> = [
    ["pitch-drift", undefined],
    ["timing-smear", undefined],
    ...eligibleSources("lossy-artifact").map((src) => ["lossy-artifact", src] as [string, string]),
  ];
  const out: StaircaseResult[] = [];
  for (const [family, sourceId] of ladders) {
    for (const place of [0, 0.25, 0.5, 0.75, 1]) {
      for (const seed of [7919, 15838]) out.push(session(family, place, seed, sourceId));
    }
  }
  return out;
}

function delicacyResult(pick: (family: string) => boolean) {
  const responses: DelicacyResponses = {};
  for (const t of MEASURED_TRIALS) {
    const ok = pick(t.family);
    responses[t.id] = {
      pickedSide: ok ? t.originalSide : t.originalSide === "a" ? "b" : "a",
      flawPick: t.family,
      confidence: 70,
    };
  }
  return computeDelicacyResult(DELICACY_INSTRUMENT_ID, MEASURED_TRIALS, responses);
}

/** All three delicacy states the copy branches on, including the zero-score one. */
export function delicacyResults() {
  return {
    all: delicacyResult(() => true),
    some: delicacyResult((f) => f !== "pitch-drift"),
    none: delicacyResult(() => false),
  };
}

function biasResult(shift: number) {
  const blind: Record<string, number> = {};
  const labeled: Record<string, number> = {};
  for (const item of BIAS_CLIPS) {
    blind[item.id] = 5;
    const toward = item.isControl ? 0 : item.labelDirection === "up" ? shift : -shift;
    labeled[item.id] = Math.max(BIAS_SCALE_MIN, Math.min(BIAS_SCALE_MAX, 5 + toward));
  }
  return computeBiasResult(BIAS_INSTRUMENT_ID, BIAS_CLIPS, blind, labeled);
}

/** One session per verdict — the only axis the prestige copy branches on. */
export function biasResults() {
  return { swayed: biasResult(2), steady: biasResult(0), contrarian: biasResult(-2) };
}

function acrossInput(thresholds: StaircaseResult[], withBias: boolean, withDelicacy: boolean): AcrossInput {
  const delicacy = withDelicacy ? delicacyResult(() => true) : null;
  const replications: ReplicationCheck[] = [];
  if (delicacy) {
    for (const t of thresholds) {
      const check = replicationCheck(t.family as DegradationFamily, delicacy, t);
      if (check.ok) replications.push(check.value);
    }
  }
  const measured = new Set(thresholds.map((t) => t.family));
  return {
    bias: withBias ? biasResult(2) : null,
    delicacy,
    thresholds,
    replications,
    unmeasured: ["pitch-drift", "timing-smear", "lossy-artifact"].filter((f) => !measured.has(f)),
  };
}

/**
 * The combined view's reachable states: two instruments and three, with and
 * without a replication, and with coverage both partial and complete.
 */
export function acrossInputs(): Record<string, AcrossInput> {
  const pitch = session("pitch-drift", 0, 7919);
  const timing = session("timing-smear", 0.4, 7919);
  const lossy = session("lossy-artifact", 0, 7919, eligibleSources("lossy-artifact")[0]);
  return {
    "bias-delicacy": acrossInput([], true, true),
    "delicacy-threshold": acrossInput([pitch], false, true),
    "no-replication": acrossInput([timing], false, true),
    "all-three": acrossInput([pitch, timing, lossy], true, true),
    "full-coverage": acrossInput([pitch, timing, lossy], true, false),
  };
}

/** The whole deck, ready for `checkVoice`. */
export function vocabularyStrings(): VoiceString[] {
  const out: VoiceString[] = [];

  for (const result of thresholdSessions()) {
    const claim = thresholdClaim(result);
    if (!claim.ok) continue;
    const tag = `${result.family}${result.sourceId ? `-${result.sourceId}` : ""}/${result.kind}`;
    thresholdLines(claim.value).forEach((text, i) => {
      out.push({ surface: `vocabulary/threshold/${tag}/${i}`, text, intensity: "pointed" });
    });
  }

  for (const [name, result] of Object.entries(delicacyResults())) {
    delicacyLines(result).forEach((text, i) => {
      out.push({ surface: `vocabulary/delicacy/${name}/${i}`, text, intensity: "pointed" });
    });
  }

  for (const [name, result] of Object.entries(biasResults())) {
    biasLines(result).forEach((text, i) => {
      out.push({ surface: `vocabulary/bias/${name}/${i}`, text, intensity: "pointed" });
    });
  }

  for (const [name, input] of Object.entries(acrossInputs())) {
    acrossLines(input).forEach((text, i) => {
      out.push({ surface: `vocabulary/across/${name}/${i}`, text, intensity: "pointed" });
    });
    thresholdRoster(input).forEach((text, i) => {
      out.push({ surface: `vocabulary/across/${name}/roster/${i}`, text, intensity: "calm" });
    });
  }

  /**
   * THE EXPERT PANEL (E8/C4). Every fixed string on the verdict-free surface,
   * plus the one composed sentence. `intensity: "calm"` throughout: this deck
   * labels measurements and states limits, and the "full" tier's datum rule
   * would wrongly demand a figure inside a column header.
   */
  for (const { key, text } of expertStrings()) {
    out.push({ surface: `vocabulary/expert/${key}`, text, intensity: "calm" });
  }
  out.push({
    surface: "vocabulary/expert/note/brier",
    text: brierNote(0.287, 15, 0.25),
    intensity: "calm",
  });

  return out;
}
