/**
 * EVERY SENTENCE THE VOCABULARY LAYER CAN EMIT (E8/S9).
 *
 * WHY A FIXTURE MODULE AND NOT A LIST. The four vocabulary modules branch on
 * band shape, on outcome kind, on verdict, on whether a family was measured,
 * and on how many instruments have run. Hand-listing the reachable sentences
 * would freeze whatever set I happened to think of; a branch nobody exercised
 * is exactly where an off-voice line survives, which is the argument
 * `staircaseCopyFixtures` already makes one directory over.
 *
 * So these are generated by driving the real engines across placements that
 * reach every branch, and the enumeration is asserted — `vocabulary.test.ts`
 * fails if a shape stops being covered.
 *
 * INTENSITY. Everything here is "pointed": these paragraphs sit beside a
 * number rather than carrying one themselves, and several are refusals, which
 * the "full" tier's datum rule would wrongly demand a figure from.
 */
import type { VoiceString } from "../voice";
import { creatorLines as thresholdLines } from "./threshold";
import { creatorLines as delicacyLines } from "./delicacy";
import { creatorLines as biasLines } from "./bias";
import { acrossLines, thresholdRoster, type AcrossInput } from "./across";
import { arcLines } from "./arc";
import { recognitionLines, SPREAD_BOUNDARY } from "./spread";
import { computeSpreadResult } from "@/engine/spread";
import { SPREAD_POOL } from "@/content/spread/ranking";
import { biasArc, delicacyArc, thresholdArc, type ArcReading } from "@/engine/arc";
import { brierNote, expertStrings } from "./expert";
import { thresholdClaim, type Claim } from "@/engine/evidence";
import { replicationCheck } from "@/engine/replication";
import type { ReplicationCheck } from "@/engine/replication";
import type { DegradationFamily } from "@/engine/delicacy";
import { DELICACY_INSTRUMENT_ID, MEASURED_TRIALS } from "@/content/delicacy/items";
import { computeDelicacyResult, type DelicacyResponses } from "@/engine/delicacy";
import { BIAS_CLIPS, BIAS_INSTRUMENT_ID } from "@/content/bias/items";
import { BIAS_SCALE_MAX, BIAS_SCALE_MIN, computeBiasResult } from "@/engine/bias";
import {
  answer,
  axisFor,
  isFinished,
  nextTrial,
  sessionResult,
  startSession,
  type StaircaseResult,
} from "@/engine/staircase-session";
import { eligibleSources } from "@/engine/staircase-pool";
import { observer, pCorrect, rng } from "@/analytics/observer";

/** A listener placed at `place` along the family's own ladder. See replication.test.ts. */
function session(family: string, place: number, seed: number, sourceId?: string): StaircaseResult {
  const mags = axisFor(family, sourceId).magnitudes;
  const lo = Math.log(mags[0] / 4);
  const hi = Math.log(mags[mags.length - 1] * 4);
  const o = observer(Math.exp(lo + (hi - lo) * place), 0.35, 0.02);
  let s = startSession(family, seed, sourceId);
  const rand = rng(seed ^ 0x5bf03635);
  while (!isFinished(s)) {
    const t = nextTrial(s);
    s = answer(s, rand() < pCorrect(s.axis.magnitudes[t.levelIndex], o));
  }
  return sessionResult(s);
}

/** Every threshold session the fixtures draw on — all ladders, all placements. */
export function thresholdSessions(): StaircaseResult[] {
  const ladders: Array<[string, string | undefined]> = [
    ["pitch-drift", undefined],
    ["timing-smear", undefined],
    ...eligibleSources("lossy-artifact").map((src) => ["lossy-artifact", src] as [string, string]),
  ];
  const out: StaircaseResult[] = [];
  for (const [family, sourceId] of ladders) {
    for (const place of [0, 0.25, 0.5, 0.75, 1]) {
      for (const seed of [7919, 15838]) out.push(session(family, place, seed, sourceId));
    }
  }
  return out;
}

function delicacyResult(pick: (family: string) => boolean) {
  const responses: DelicacyResponses = {};
  for (const t of MEASURED_TRIALS) {
    const ok = pick(t.family);
    responses[t.id] = {
      pickedSide: ok ? t.originalSide : t.originalSide === "a" ? "b" : "a",
      flawPick: t.family,
      confidence: 70,
    };
  }
  return computeDelicacyResult(DELICACY_INSTRUMENT_ID, MEASURED_TRIALS, responses);
}

/** All three delicacy states the copy branches on, including the zero-score one. */
export function delicacyResults() {
  return {
    all: delicacyResult(() => true),
    some: delicacyResult((f) => f !== "pitch-drift"),
    none: delicacyResult(() => false),
  };
}

/**
 * A prestige session where each scored clip moves by its own whole number of
 * rating points. Whole numbers because the engine rejects anything else, which
 * is the mechanism behind the lattice E14/S1 found in the headline.
 */
function biasResultBy(shiftFor: (index: number) => number) {
  const blind: Record<string, number> = {};
  const labeled: Record<string, number> = {};
  let scored = 0;
  for (const item of BIAS_CLIPS) {
    blind[item.id] = 5;
    const shift = item.isControl ? 0 : shiftFor(scored++);
    const toward = item.labelDirection === "up" ? shift : -shift;
    labeled[item.id] = Math.max(BIAS_SCALE_MIN, Math.min(BIAS_SCALE_MAX, 5 + toward));
  }
  return computeBiasResult(BIAS_INSTRUMENT_ID, BIAS_CLIPS, blind, labeled);
}

function biasResult(shift: number) {
  return biasResultBy(() => shift);
}

/** One session per verdict — the only axis the prestige copy branches on. */
export function biasResults() {
  return { swayed: biasResult(2), steady: biasResult(0), contrarian: biasResult(-2) };
}

/**
 * EVERY ARC BRANCH, DRIVEN THROUGH THE REAL COMPARISON (E14/S3).
 *
 * The arc has more shapes than any other module here — three directions, an
 * off-ladder case, and five refusals — and a hand-written list of readings
 * would freeze whatever set I thought of, which is the argument this file
 * already makes at the top. So the readings come out of `thresholdArc` and
 * `biasArc` on real sessions, and the refusals come out of the real refusal
 * paths rather than being typed as gap strings.
 *
 * The listener placements are chosen so each branch is REACHED, and
 * `arc.test.ts` asserts that they still are — a silent placement drift would
 * leave a branch unvoiced, which is exactly where an off-voice line survives.
 */
function arcSession(family: string, place: number, seed: number, sourceId?: string) {
  const mags = axisFor(family, sourceId).magnitudes;
  const lo = Math.log(mags[0] / 4);
  const hi = Math.log(mags[mags.length - 1] * 4);
  const o = observer(Math.exp(lo + (hi - lo) * place), 0.35, 0.02);
  let s = startSession(family, seed, sourceId);
  const rand = rng(seed ^ 0x5bf03635);
  while (!isFinished(s)) {
    const t = nextTrial(s);
    s = answer(s, rand() < pCorrect(s.axis.magnitudes[t.levelIndex], o));
  }
  return s;
}

const pair = (a: ReturnType<typeof arcSession>, b: ReturnType<typeof arcSession>) => [
  { at: 1_000, session: a },
  { at: 2_000, session: b },
];

export function arcClaims(): Record<string, Claim<ArcReading>> {
  const PITCH = "pitch-drift";
  const lossy = eligibleSources("lossy-artifact");
  // Two sittings by the same person, well apart and both inside the ladder.
  const sharpBefore = arcSession(PITCH, 0.65, 7919);
  const sharpAfter = arcSession(PITCH, 0.35, 15838);
  return {
    // Same listener twice: the ordinary outcome, and the one most readers see.
    "threshold-no-change": thresholdArc(pair(arcSession(PITCH, 0.5, 7919), arcSession(PITCH, 0.5, 15838))),
    /*
     * A listener who genuinely sharpened, and one who genuinely dulled — BOTH
     * SITTINGS INSIDE THE LADDER. The first version used 0.75 and 0.2, which
     * `session`'s placement scale puts past the rungs (it spans a quarter of
     * the floor to four times the ceiling), so both fixtures rendered the
     * OFF-LADDER sentence and the ordinary one was never voiced at all. Nothing
     * failed: the directions were right and the deck was clean. It was found by
     * reading the printed sentences, and `arc.test.ts` now asserts the range as
     * well as the direction.
     */
    "threshold-closer": thresholdArc(pair(sharpBefore, sharpAfter)),
    /*
     * FOUR SITTINGS, so the pooled sentence is reached (E14/S6). Without a
     * fixture at this length the only sentence describing what coming back buys
     * would never be rendered by anything — unvoiced, unread and unchecked,
     * which is the hole this file exists to close.
     */
    "threshold-pooled": thresholdArc([
      { at: 1_000, session: arcSession(PITCH, 0.65, 3001) },
      { at: 2_000, session: sharpBefore },
      { at: 3_000, session: arcSession(PITCH, 0.35, 4001) },
      { at: 4_000, session: sharpAfter },
    ]),
    /*
     * THE SAME TWO SESSIONS, THE OTHER WAY ROUND. Not a second pair of
     * placements: the first attempt used (0.35, 0.65) against (0.65, 0.35) with
     * the seeds held in place, which pairs each observer with a DIFFERENT
     * session, and one of those pairs came out 3.0x apart — under the 3.5x
     * floor — so the "further" branch silently stopped being reached. Reversing
     * one pair makes the distance identical by construction and leaves only the
     * thing being tested, which is that order decides the sign.
     */
    "threshold-further": thresholdArc(pair(sharpAfter, sharpBefore)),
    // One sitting off the end of what the ladder can render.
    "threshold-off-ladder": thresholdArc(pair(arcSession(PITCH, 0.55, 7919), arcSession(PITCH, 0.0, 15838))),
    /*
     * A REAL gap that is still under the floor, not two identical sessions. The
     * first version compared a session with itself, so the sentence rendered
     * "+20% last time and +20% this time" — technically the null branch, and a
     * fixture that could never have caught the sentence saying something wrong
     * about a gap, because it had no gap.
     */
    "bias-no-change": biasArc([
      { at: 1_000, result: biasResult(2) },
      { at: 2_000, result: biasResultBy((i) => (i % 2 === 0 ? 2 : 1)) },
    ]),
    "bias-closer": biasArc([
      { at: 1_000, result: biasResult(2) },
      { at: 2_000, result: biasResult(0) },
    ]),
    "bias-further": biasArc([
      { at: 1_000, result: biasResult(0) },
      { at: 2_000, result: biasResult(2) },
    ]),
    "refuse-too-few": thresholdArc([{ at: 1_000, session: arcSession(PITCH, 0.5, 7919) }]),
    "refuse-different-material": thresholdArc(
      pair(
        arcSession("lossy-artifact", 0.5, 7919, lossy[0]),
        arcSession("lossy-artifact", 0.5, 15838, lossy[1]),
      ),
    ),
    "refuse-delicacy": delicacyArc(),
    "refuse-no-floor": thresholdArc(
      pair(arcSession(PITCH, 0.5, 7919), arcSession(PITCH, 0.5, 15838)).map((e) => ({
        ...e,
        session: { ...e.session, family: "invented-family" },
      })),
    ),
  };
}

function acrossInput(thresholds: StaircaseResult[], withBias: boolean, withDelicacy: boolean): AcrossInput {
  const delicacy = withDelicacy ? delicacyResult(() => true) : null;
  const replications: ReplicationCheck[] = [];
  if (delicacy) {
    for (const t of thresholds) {
      const check = replicationCheck(t.family as DegradationFamily, delicacy, t);
      if (check.ok) replications.push(check.value);
    }
  }
  const measured = new Set(thresholds.map((t) => t.family));
  return {
    bias: withBias ? biasResult(2) : null,
    delicacy,
    thresholds,
    replications,
    unmeasured: ["pitch-drift", "timing-smear", "lossy-artifact"].filter((f) => !measured.has(f)),
  };
}

/**
 * The combined view's reachable states: two instruments and three, with and
 * without a replication, and with coverage both partial and complete.
 */
export function acrossInputs(): Record<string, AcrossInput> {
  const pitch = session("pitch-drift", 0, 7919);
  const timing = session("timing-smear", 0.4, 7919);
  const lossy = session("lossy-artifact", 0, 7919, eligibleSources("lossy-artifact")[0]);
  return {
    "bias-delicacy": acrossInput([], true, true),
    "delicacy-threshold": acrossInput([pitch], false, true),
    "no-replication": acrossInput([timing], false, true),
    "all-three": acrossInput([pitch, timing, lossy], true, true),
    "full-coverage": acrossInput([pitch, timing, lossy], true, false),
  };
}

/** The whole deck, ready for `checkVoice`. */

/**
 * A rating for every clip in the critic-ranked pool. Values chosen to be
 * uneven rather than realistic: the copy branches on COUNTS, never on the
 * ratings themselves, so what matters is that every clip carries one.
 */
export function spreadRatings(): Record<string, number> {
  const values = [9, 2, 7, 1, 8, 3];
  return Object.fromEntries(SPREAD_POOL.map((item, n) => [item.id, values[n % values.length]]));
}

/** Every state the recognition filter can reach, by which clips were set aside. */
export function spreadRecognitionCases(): Record<string, string[]> {
  return {
    none: [],
    "one-still-readable": ["sp2"],
    "far-pairs-collapse": ["sp1"],
    "close-pairs-collapse": ["sp2", "sp3"],
    all: SPREAD_POOL.map((i) => i.id),
  };
}

export function vocabularyStrings(): VoiceString[] {
  const out: VoiceString[] = [];

  for (const result of thresholdSessions()) {
    const claim = thresholdClaim(result);
    if (!claim.ok) continue;
    const tag = `${result.family}${result.sourceId ? `-${result.sourceId}` : ""}/${result.kind}`;
    thresholdLines(claim.value).forEach((text, i) => {
      out.push({ surface: `vocabulary/threshold/${tag}/${i}`, text, intensity: "pointed" });
    });
  }

  for (const [name, result] of Object.entries(delicacyResults())) {
    delicacyLines(result).forEach((text, i) => {
      out.push({ surface: `vocabulary/delicacy/${name}/${i}`, text, intensity: "pointed" });
    });
  }

  for (const [name, result] of Object.entries(biasResults())) {
    biasLines(result).forEach((text, i) => {
      out.push({ surface: `vocabulary/bias/${name}/${i}`, text, intensity: "pointed" });
    });
  }

  for (const [name, input] of Object.entries(acrossInputs())) {
    acrossLines(input).forEach((text, i) => {
      out.push({ surface: `vocabulary/across/${name}/${i}`, text, intensity: "pointed" });
    });
    thresholdRoster(input).forEach((text, i) => {
      out.push({ surface: `vocabulary/across/${name}/roster/${i}`, text, intensity: "calm" });
    });
  }

  for (const [name, claim] of Object.entries(arcClaims())) {
    arcLines(claim).forEach((text, i) => {
      out.push({ surface: `vocabulary/arc/${name}/${i}`, text, intensity: "pointed" });
    });
  }

  /**
   * TRACK N's recognition filter (E17/S4). Every reachable state of the
   * filter, driven through the real engine: nothing recognised, some
   * recognised with a reading still possible, and each way the evidence can
   * run out. The refusals are why `intensity` is "pointed" here too — a
   * refusal carries no datum and the "full" tier would wrongly demand one.
   */
  for (const [name, recognised] of Object.entries(spreadRecognitionCases())) {
    const result = computeSpreadResult(spreadRatings(), recognised);
    recognitionLines(result).forEach((text, i) => {
      out.push({ surface: `vocabulary/spread/${name}/${i}`, text, intensity: "pointed" });
    });
  }
  out.push({ surface: "vocabulary/spread/boundary", text: SPREAD_BOUNDARY, intensity: "pointed" });

  /**
   * THE EXPERT PANEL (E8/C4). Every fixed string on the verdict-free surface,
   * plus the one composed sentence. `intensity: "calm"` throughout: this deck
   * labels measurements and states limits, and the "full" tier's datum rule
   * would wrongly demand a figure inside a column header.
   */
  for (const { key, text } of expertStrings()) {
    out.push({ surface: `vocabulary/expert/${key}`, text, intensity: "calm" });
  }
  out.push({
    surface: "vocabulary/expert/note/brier",
    text: brierNote(0.287, 15, 0.25),
    intensity: "calm",
  });

  return out;
}
