/**
 * NO ROUTE RENDERS TEXT A MODEL WROTE (owner ruling BA-10, 2026-09-23).
 *
 * Templates only: no model writes any part of the reading, the prompt, or any
 * other sentence a visitor reads. Until this ruling the snack's verdict was
 * model-written, and on 2026-09-23 it rendered "headphones are cheaper than
 * therapy" — a sentence under the mental-health carve-out that no template
 * guard could see, because no template contained it.
 *
 * SO THIS READS THE IMPORT GRAPH, NOT A LIST. From every page, layout, API
 * route and metadata route under `src/app` (the walker is shared, in
 * `src/test-utils/import-graph.ts`), it follows every import into `src/` and fails if any
 * reachable module imports a model SDK or calls a model provider's API. A list
 * of forbidden files would pass the day somebody wrote a new narrator under a
 * new name; the graph cannot.
 *
 * It also holds `package.json` free of a model SDK, so the dependency cannot
 * return quietly in a lockfile update.
 *
 * WHAT IT CANNOT SEE: a model reached from outside `src/` (a script, a build
 * step) whose output is then committed as a template. A template is a sentence
 * somebody chose to ship; where they got it is on them.
 *
 * AND THE SITE MUST NOT SAY OTHERWISE (N3, 2026-09-24). The import graph proves
 * no model writes a sentence; it cannot see a sentence CLAIMING one does. On
 * 2026-09-24 /learn/methodology still read "Where an AI writes narrative around
 * a result, it narrates a number…", and /llms-full.txt said the same to every
 * AI crawler, a day after BA-10 made it false. The second half of this file
 * reads every rendered page, its metadata, and both llms files, and fails on an
 * affirmative claim that a model writes, narrates or generates what a visitor
 * reads. Denials ("No sentence … is generated by a language model") and history
 * in the past tense ("its verdict was written by a language model") pass: the
 * claim must be present-tense and un-negated within its own clause.
 */
import { readFileSync } from "node:fs";
import { beforeAll, describe, expect, it, vi } from "vitest";
import { appEntries, resolve, specifiers, walk } from "@/test-utils/import-graph";
import { renderSite, textOf, type RenderedSite } from "@/test-utils/render-site";

vi.mock("next/navigation", async (orig) => ({
  ...(await orig<typeof import("next/navigation")>()),
  useRouter: () => ({ push() {}, replace() {}, prefetch() {}, back() {}, forward() {}, refresh() {} }),
  usePathname: () => globalThis.__SITE_PATH ?? "/",
  useSearchParams: () => new URLSearchParams(),
}));
// The root layout loads fonts at module scope; only its metadata is read here.
vi.mock("next/font/google", () => ({ Geist: () => ({ variable: "" }), Geist_Mono: () => ({ variable: "" }) }));
vi.mock("next/font/local", () => ({ default: () => ({ variable: "" }) }));

/** Packages that are model clients. */
const MODEL_SDKS = [
  "@anthropic-ai/sdk",
  "openai",
  "@google/generative-ai",
  "@google/genai",
  "@mistralai/mistralai",
  "cohere-ai",
  "ai",
  "@ai-sdk/anthropic",
  "@ai-sdk/openai",
];
/** A raw call to a provider, without an SDK. */
const MODEL_HOSTS = /api\.anthropic\.com|api\.openai\.com|generativelanguage\.googleapis\.com|api\.mistral\.ai|api\.cohere\.(ai|com)/;

/** Why a single file is a model client, or null. */
function modelUse(file: string): string | null {
  const sdk = specifiers(file).find((s) => MODEL_SDKS.some((p) => s === p || s.startsWith(`${p}/`)));
  if (sdk) return `imports ${sdk}`;
  if (MODEL_HOSTS.test(readFileSync(file, "utf8"))) return "calls a model provider's API";
  return null;
}

/** The first chain from an entry to a model client, or null. */
function chainToModel(entry: string, classify = modelUse): string[] | null {
  const seen = new Set<string>();
  const stack: string[][] = [[entry]];
  while (stack.length) {
    const path = stack.pop()!;
    const file = path[path.length - 1];
    if (seen.has(file)) continue;
    seen.add(file);
    const why = classify(file);
    if (why) return [...path, why];
    for (const spec of specifiers(file)) {
      const next = resolve(file, spec);
      if (next && !seen.has(next)) stack.push([...path, next]);
    }
  }
  return null;
}

describe("no page or API route reaches a model (BA-10)", () => {
  const all = appEntries();

  it("found the site's entry points (a floor, so an empty walk cannot pass)", () => {
    // Measured 2026-09-23 after the model routes were deleted: 40 entries; 57 on
    // 2026-09-24, counting the metadata routes the first walker missed.
    expect(all.length).toBeGreaterThanOrEqual(35);
    expect(all.some((f) => f.endsWith("/api/bias-card/route.tsx"))).toBe(true);
    // Next's metadata routes and the global error page are entries too (2026-09-24:
    // the first walker missed them, so a model called from the share image passed).
    for (const f of ["src/app/opengraph-image.tsx", "src/app/icon.tsx", "src/app/sitemap.ts", "src/app/global-error.tsx"]) {
      expect(all, `${f} is not walked`).toContain(f);
    }
  });

  it("follows imports through the graph, not just the entry file", () => {
    // A synthetic client two hops from a real page: the walker must find it.
    const planted = chainToModel("src/app/lab/data-model/page.tsx", (f) =>
      f === "src/lib/events.ts" ? "planted for this test" : modelUse(f),
    );
    expect(planted, "the walker did not reach src/lib/events.ts (two hops) from /lab/data-model").not.toBeNull();
    expect(planted!.length, "the chain skipped the middle hop").toBeGreaterThanOrEqual(4);
  });

  it("reaches no module that imports a model SDK or calls a provider", () => {
    const found = all.flatMap((e) => {
      const chain = chainToModel(e);
      return chain ? [chain.join(" -> ")] : [];
    });
    expect(found).toEqual([]);
  });

  it("imports no model SDK anywhere in src/, reachable or not", () => {
    const found = walk("src")
      .filter((f) => /\.(ts|tsx|mjs|js)$/.test(f) && !/\.test\.tsx?$/.test(f))
      .flatMap((f) => (modelUse(f) ? [`${f}: ${modelUse(f)}`] : []));
    expect(found).toEqual([]);
  });

  it("does not depend on a model SDK", () => {
    const pkg = JSON.parse(readFileSync("package.json", "utf8"));
    const deps = Object.keys({ ...pkg.dependencies, ...pkg.devDependencies });
    expect(deps.filter((d) => MODEL_SDKS.includes(d))).toEqual([]);
  });
});

/**
 * A claim that a model authors text. The subject is AI, an LLM, a (language)
 * model, or a model family by name; the verb is one of authorship, in ANY tense.
 * Past tense is not exempt by grammar — "your reading was generated by a model"
 * is a present claim in the past tense — so history is exempted by name, below.
 */
const MODEL = String.raw`(?:AI|LLMs?|(?:language\s+)?models?|Claude|ChatGPT|GPT(?:-\d[\w.]*)?|Gemini|Llama|Mistral)`;
const AUTHORSHIP_CLAIM = [
  new RegExp(String.raw`\b${MODEL}\s+(?:writes?|wrote|narrates?|narrated|generates?|generated|composes?|composed|drafts?|drafted)\b`, "i"),
  new RegExp(String.raw`\b${MODEL}[- ](?:written|generated|narrated|authored|composed|drafted)\b`, "i"),
  new RegExp(String.raw`\b(?:is|are|was|were|gets?|got|been|be)\s+(?:written|generated|narrated|composed|drafted|authored)\s+by\s+(?:an?\s+|the\s+)?${MODEL}\b`, "i"),
];
/** A negation earlier in the same clause turns a claim into a denial. */
const NEGATION = /\b(?:no|not|never|nothing|none|neither|nor|without)\b|n't\b/i;
/**
 * Clauses end at punctuation AND at "and"/"but", so a negation in one half of
 * "No sign-up needed and an AI writes your reading" cannot excuse the other.
 */
const CLAUSE_BREAK = /[.!?;:,\n—–]+|\s(?:and|but)\s/i;

/**
 * History the site keeps on purpose, exempted by exact clause and route. Each
 * entry must still be found where it says, or the exemption test fails, so an
 * exemption cannot outlive the sentence it was written for.
 */
const HISTORY: readonly { route: string; clause: string; why: string }[] = [
  {
    route: "/method",
    clause: "and its verdict was written by a language model",
    why: "the third reversal records why the snack was retired (BA-7, BA-10)",
  },
];

/** The clauses of `text` that claim a model writes what the reader reads. */
function authorshipClaims(text: string): string[] {
  return text
    .split(/[.!?;:,\n—–]+/)
    .flatMap((sentencePart) => {
      // Keep the raw part for reporting; test each and/but half separately.
      const halves = sentencePart.split(CLAUSE_BREAK);
      const hit = halves.some((half) =>
        AUTHORSHIP_CLAIM.some((re) => {
          const m = re.exec(half);
          return m !== null && !NEGATION.test(half.slice(0, m.index));
        }),
      );
      return hit ? [sentencePart.replace(/\s+/g, " ").trim()] : [];
    });
}

describe("no page claims a model writes what the visitor reads (BA-10, N3)", () => {
  let site: RenderedSite;
  const LLMS = ["public/llms.txt", "public/llms-full.txt"];

  beforeAll(async () => {
    site = await renderSite();
  }, 60_000);

  it("rendered the site, so the scan below cannot pass on nothing", () => {
    expect(site.failed).toEqual([]);
    // Measured 2026-09-24: 30 pages render, 8 redirect.
    expect(site.pages.length).toBeGreaterThanOrEqual(25);
    expect(site.pages.map((p) => p.route)).toContain("/learn/methodology");
  });

  it("the matcher catches the claims it exists for, and lets denials and history through", () => {
    // The two sentences that were live on 2026-09-24.
    expect(authorshipClaims("Where an AI writes narrative around a result, it narrates a number.")).toHaveLength(1);
    expect(authorshipClaims("Where AI writes narrative, it narrates an already-computed number.")).toHaveLength(1);
    expect(authorshipClaims("Your reading is generated by a language model.")).toHaveLength(1);
    expect(authorshipClaims("An AI-written summary follows.")).toHaveLength(1);
    // Red-team, 2026-09-24: a named model, a negation borrowed from the other
    // half of an "and", and a present claim in the past tense each passed the
    // first version of this matcher.
    expect(authorshipClaims("Claude drafts your reading from your plays.")).toHaveLength(1);
    expect(authorshipClaims("GPT-4o writes the summary.")).toHaveLength(1);
    expect(authorshipClaims("No sign-up needed and an AI writes your reading.")).toHaveLength(1);
    expect(authorshipClaims("Your reading was generated by a language model.")).toHaveLength(1);
    // Denials, as the site states them today.
    expect(authorshipClaims("No sentence on this site is generated by a language model when you visit.")).toEqual([]);
    expect(authorshipClaims("No model writes any sentence, and nothing on any surface asserts anything.")).toEqual([]);
    expect(authorshipClaims("Every sentence is a fixed template; no language model writes any of it.")).toEqual([]);
    expect(authorshipClaims("No language model classifies you, no black box guesses.")).toEqual([]);
    expect(authorshipClaims("by one owner and an AI engineer, under a written constitution")).toEqual([]);
  });

  it("no rendered page, and no page's metadata, claims one outside the named history", () => {
    const found = site.pages.flatMap((p) =>
      authorshipClaims([textOf(p.html), ...p.meta].join("\n"))
        .filter((c) => !HISTORY.some((h) => h.route === p.route && h.clause === c))
        .map((c) => `${p.route}: "${c}"`),
    );
    expect(found).toEqual([]);
  });

  it("every history exemption is still found where it says, so none outlives its sentence", () => {
    for (const h of HISTORY) {
      const page = site.pages.find((p) => p.route === h.route);
      expect(page, `${h.route} did not render`).toBeDefined();
      const claims = authorshipClaims([textOf(page!.html), ...page!.meta].join("\n"));
      expect(claims, `exemption for ${h.route} (${h.why}) matches nothing; delete it`).toContain(h.clause);
    }
  });

  it("neither llms file claims one", () => {
    const found = LLMS.flatMap((f) => authorshipClaims(readFileSync(f, "utf8")).map((c) => `${f}: "${c}"`));
    expect(found).toEqual([]);
  });
});
