/**
 * E6/S7 — WHAT TEN MINUTES OF THE DELICACY TRIALS BUYS [SIMULATED].
 *
 * The sharper half of E6. The scored count of 15 was chosen on 2026-08-08 as
 * "analysable without a session nobody finishes" — an ROI judgment made before
 * the rate framing existed — while Spearman-Brown put alpha 0.70 near 42
 * trials. Those two numbers have never been reconciled, and the session has
 * been shipping at 15 ever since.
 *
 * TWO CRITERIA, BECAUSE THE INSTRUMENT SERVES TWO MASTERS. I expected them to
 * want different session lengths and wrote that down before measuring. They do
 * not. They converge on the same answer from opposite directions, which is a
 * better result than the one I predicted:
 *
 *   INDIVIDUAL — `delicacyVerdict` places a person in a tier from
 *     above = (nCorrect - n/2) / (n/2). That is what one human reads. The gate
 *     is how often the tier is the RIGHT tier, exactly as E6/S6 gated the
 *     Prestige verdict against its own +/-15% lines.
 *
 *   COHORT — alpha and split-half reliability decide whether the response set
 *     can carry item analysis, IRT and the Lab at all. That is where the 42
 *     came from. It is a property of the MATRIX, not of any person, and no
 *     individual's result gets better or worse because of it.
 *
 * The 42-trial figure answers the cohort question. It was never an answer to
 * the individual one, and the session length was set as if it were.
 *
 * ================================ THE ANSWER ================================
 *
 * AT THE SHIPPING LENGTH THE VERDICT IS WRONG ALMOST HALF THE TIME. Fifteen
 * scored trials place a person in the right tier 57.5% of the time on the
 * synthetic bank and 54.2% on the live pool. The Prestige Test, measured the
 * same way in E6/S6, manages 89.3%.
 *
 * THE CAUSE IS RESOLUTION, NOT LENGTH PER SE. At 15 trials the SD of a person's
 * measured share-correct is 0.106, while the narrowest shipped tier is 0.125
 * wide — a band 1.18 SD across. The ruler is nearly as wide as the thing it is
 * measuring. Six tiers on the chance-to-perfect range need about six times 2 SD
 * of room; 15 trials supply enough for about two.
 *
 * BOTH CRITERIA LAND ON ~42-45 TRIALS, BY DIFFERENT ROUTES. Cohort reliability
 * crosses alpha 0.70 at 42 (reproducing the 2026-08-08 Spearman-Brown figure
 * from a fresh simulation), and the narrowest tier crosses 2 SD at about 45.
 * Two unrelated arguments arriving at the same number is the strongest thing in
 * this slice.
 *
 * AND 42 TRIALS IS 21 MINUTES — which is exactly the session nobody finishes
 * that 15 was chosen to avoid. So the honest options are not "15 or 42". They
 * are: buy the resolution with minutes, or STOP PRINTING RESOLUTION THAT IS NOT
 * THERE and say less at 15. The second is free, and it is the one the measured
 * numbers support.
 *
 * See `docs/analytics/e6-delicacy.txt`, regenerated by this test.
 *
 * ITEMS BEYOND THE LIVE POOL ARE SYNTHETIC AND SAID SO (N3). Only 18 pairs
 * exist — 3 practice, 15 scored — so every length past 15 is a claim about a
 * pool we would have to author, not about the one we ship. The curve is
 * therefore run entirely on the synthetic bank, so that every point is
 * comparable to every other; the live pool's own point is reported separately
 * and labelled.
 *
 * EVERYTHING HERE IS SIMULATED (N3). Zero real responses.
 */

import { describe, it, expect } from "vitest";
import { writeFileSync, mkdirSync } from "node:fs";
import { MEASURED_TRIALS } from "@/content/delicacy/items";

import {
  assignDelicacyParams,
  simulateDelicacy,
  simulatePersons,
  syntheticDelicacyItems,
  pCorrectSide,
  DEFAULT_PERSON_MODEL,
  SIMULATED,
  type SimDelicacyItem,
} from "./simulate";
import { delicacyMatrix, estimateReliability } from "./estimate";
import { MIN_LISTEN_MS_PER_CLIP, REPLAY_FACTOR } from "@/engine/staircase-session";

/**
 * THE RETIRED SHIPPING TIERS, kept here as the SUBJECT of the measurement that
 * retired them (E6/S23).
 *
 * These six verdicts shipped on the delicacy result until E6/S9-S11 replaced
 * them with a detection band. They were removed from the copy deck because no
 * surface renders them any more and dead product code is how a retired thing
 * gets accidentally re-wired.
 *
 * They live on HERE because the E6/S7 and S8 analyses are about them: the
 * finding is that these tiers place a person correctly 30.5% of the time at
 * fifteen trials, and that no coarser cut reaches the 89.3% the Prestige
 * verdict manages. An analysis whose subject has been deleted is unreadable,
 * and re-deriving the boundaries from prose later would be worse than keeping
 * the function that defined them.
 *
 * VERBATIM from `src/content/delicacy/copy.ts` at commit a98a634. Do not
 * "improve" it — it is a record of what shipped, not code with a future.
 */
interface RetiredVerdict {
  title: string;
  sub: string;
}

function delicacyVerdict(nCorrect: number, nTrials: number): RetiredVerdict {
  const chance = String(nTrials / 2);
  const headroom = nTrials / 2;
  const above = (nCorrect - nTrials / 2) / headroom;

  if (nCorrect === nTrials)
    return { title: "The key in the wine.", sub: `All ${nTrials} flaws found. Sancho's kinsmen would pour you a glass.` };
  if (above >= 0.75)
    return { title: "Sharp ears.", sub: `${nCorrect} of ${nTrials}, against a coin flip's ${chance}. Very little got past you.` };
  if (above >= 0.4)
    return { title: "Better than the coin.", sub: `${nCorrect} of ${nTrials} — the coin calls ${chance}. You hear something real.` };
  if (above > 0)
    return { title: "A hair above chance.", sub: `${nCorrect} of ${nTrials}, and the coin calls ${chance}. Not nothing — barely.` };
  if (above === 0)
    return { title: "The coin ties you.", sub: `A flipped coin calls ${chance} of ${nTrials}. So did you.` };
  return { title: "The village.", sub: `${nCorrect} of ${nTrials}, under the coin's ${chance}. You laughed at the tasters.` };
}

const NL = String.fromCharCode(10);
const OUT_DIR = "docs/analytics";

/** The one minutes model, imported not retyped — a trial is two clips. */
function delicacyMinutes(nTrials: number): number {
  return (nTrials * 2 * (MIN_LISTEN_MS_PER_CLIP / 1000) * REPLAY_FACTOR) / 60;
}

/**
 * The tier a person lands in, keyed by the verdict copy itself rather than by
 * a second copy of the boundaries. `delicacyVerdict` owns where the lines are;
 * duplicating 0.4 and 0.75 here would be the two-tables defect, and it would
 * silently stop measuring the product the day someone moved a line.
 */
function tierOf(nCorrect: number, nTrials: number): string {
  return delicacyVerdict(nCorrect, nTrials).title;
}

/**
 * THE WIDTH OF THE NARROWEST SHIPPED TIER, in share-correct units, READ OFF
 * `delicacyVerdict` rather than restated.
 *
 * This replaced a broken metric and the failure is worth keeping in view. The
 * first version asked how often the test agrees on "is this person above
 * chance", got 95.9% at the shipping length, and nearly reported it as proof
 * that the data supports a coarse call. It proves nothing: `pCorrectSide` is
 * `0.5 + 0.5*logistic(...)`, so EVERY simulated person's true rate is above
 * 0.5 by construction. The comparison had one class in it. 95.9% was a base
 * rate wearing the costume of an accuracy.
 *
 * What can be asked honestly, using only constants the product already ships:
 * how wide is a tier compared with the measurement error at this length? A
 * boundary can only be resolved if the band between boundaries is wide relative
 * to the noise; a tier thinner than about 2 SD is a distinction the trials
 * cannot carry, however confidently the copy states it.
 */
function narrowestTierWidth(): number {
  // Sample the shipped verdict finely and find where the title changes. 2000
  // steps puts the boundary within 0.0005 of share, which is two orders below
  // the widths being compared.
  const N = 2000;
  const bounds: number[] = [];
  let prev = tierOf(N, N); // start at perfect and walk down
  for (let k = N; k >= N / 2; k--) {
    const t = tierOf(k, N);
    if (t !== prev) {
      bounds.push(k / N);
      prev = t;
    }
  }
  // Tier edges in share units, from perfect down to chance.
  const edges = [1, ...bounds, 0.5];
  let narrowest = Infinity;
  for (let i = 1; i < edges.length; i++) {
    const w = edges[i - 1] - edges[i];
    // `delicacyVerdict` has two EXACT-EQUALITY tiers — a perfect score and an
    // exact tie with the coin. Those are single points, not bands, and they
    // show up in this scan as one sampling step wide. A point cannot be too
    // narrow to resolve, so anything at the sampling floor is dropped rather
    // than reported as the narrowest tier (the first run returned 0.00 for
    // every length, which is what a single-step artifact looks like).
    if (w > 3 / N) narrowest = Math.min(narrowest, w);
  }
  return narrowest;
}

/**
 * A person's TRUE tier: the tier their expected score falls in, with the
 * binomial noise removed. Independent of n by construction, since
 * above = 2*mean(p) - 1.
 */
function trueTier(items: SimDelicacyItem[], theta: number, nTrials: number): string {
  const meanP = items.reduce((a, it) => a + pCorrectSide(it, theta), 0) / items.length;
  return tierOf(Math.round(meanP * nTrials), nTrials);
}

interface Row {
  n: number;
  minutes: number;
  tierAgree: number;
  alpha: number;
  splitHalf: number;
  /** SD of (observed share correct - true share correct), in share units. */
  sdShare: number;
  /**
   * The narrowest shipped tier, measured in units of this length's own SD.
   * Below about 2, the tier is thinner than the ruler and the verdict is
   * printing resolution the trials do not contain.
   */
  narrowestTierInSd: number;
  /**
   * How many tiers the chance-to-perfect range can actually carry at this
   * length, at 2 SD per band. This is the number the copy should not exceed.
   */
  tiersSupported: number;
}

function measure(nTrials: number, nPersons: number, seed: number): Row {
  const items = syntheticDelicacyItems(seed, nTrials);
  const persons = simulatePersons(seed, nPersons, DEFAULT_PERSON_MODEL);
  const data = simulateDelicacy(seed, items, persons);
  const matrix = delicacyMatrix(SIMULATED, items, data.responses);
  const rel = estimateReliability(matrix);

  let agreed = 0;
  const errs: number[] = [];
  for (const [i, person] of persons.entries()) {
    const nCorrect = matrix.correct[i].filter(Boolean).length;
    if (tierOf(nCorrect, nTrials) === trueTier(items, person.theta, nTrials)) agreed++;
    const trueShare = items.reduce((a, it) => a + pCorrectSide(it, person.theta), 0) / items.length;
    errs.push(nCorrect / nTrials - trueShare);
  }
  const mean = errs.reduce((a, b) => a + b, 0) / errs.length;
  const variance = errs.reduce((a, b) => a + (b - mean) ** 2, 0) / (errs.length - 1);

  return {
    n: nTrials,
    minutes: delicacyMinutes(nTrials),
    tierAgree: agreed / persons.length,
    alpha: rel.alpha ?? Number.NaN,
    splitHalf: rel.splitHalf ?? Number.NaN,
    sdShare: Math.sqrt(variance),
    narrowestTierInSd: narrowestTierWidth() / Math.sqrt(variance),
    // The reportable range runs from chance (0.5) to perfect (1.0).
    tiersSupported: 0.5 / (2 * Math.sqrt(variance)),
  };
}

const LENGTHS = [6, 10, 15, 20, 25, 30, 42, 60];

describe("E6/S7 — the delicacy session, priced two ways [SIMULATED]", () => {
  it("measures individual tier accuracy and cohort reliability against length", { timeout: 300_000 }, () => {
    const REPLICATES = 6;
    const rows: Row[] = LENGTHS.map((n) => {
      const reps = Array.from({ length: REPLICATES }, (_, r) => measure(n, 900, 20260821 + r * 7919));
      const mean = (f: (x: Row) => number) => reps.reduce((a, c) => a + f(c), 0) / reps.length;
      return {
        n,
        minutes: delicacyMinutes(n),
        tierAgree: mean((x) => x.tierAgree),
        alpha: mean((x) => x.alpha),
        splitHalf: mean((x) => x.splitHalf),
        sdShare: mean((x) => x.sdShare),
        narrowestTierInSd: mean((x) => x.narrowestTierInSd),
        tiersSupported: mean((x) => x.tiersSupported),
      };
    });

    // The live pool's own point, kept separate because it is 15 REAL items with
    // assigned parameters, not 15 draws from the synthetic bank.
    const liveItems = assignDelicacyParams(MEASURED_TRIALS);
    const livePersons = simulatePersons(20260821, 900, DEFAULT_PERSON_MODEL);
    const liveData = simulateDelicacy(20260821, liveItems, livePersons);
    const liveMatrix = delicacyMatrix(SIMULATED, liveItems, liveData.responses);
    const liveRel = estimateReliability(liveMatrix);
    let liveAgreed = 0;
    for (const [i, person] of livePersons.entries()) {
      const nCorrect = liveMatrix.correct[i].filter(Boolean).length;
      if (tierOf(nCorrect, liveItems.length) === trueTier(liveItems, person.theta, liveItems.length)) {
        liveAgreed++;
      }
    }

    mkdirSync(OUT_DIR, { recursive: true });
    writeFileSync(
      `${OUT_DIR}/e6-delicacy.txt`,
      [
        "E6/S7 DELICACY TRIALS — LENGTH vs WHAT IT BUYS [SIMULATED, zero real responses]",
        `${REPLICATES} replicates x 900 simulated persons per length, synthetic item bank.`,
        "Lengths past 15 describe a pool we would have to AUTHOR — only 18 pairs exist.",
        "",
        "  n   minutes   tier-agree    alpha   split-half   SD(share)   tier/SD   tiers supported",
        ...rows.map(
          (r) =>
            ` ${String(r.n).padStart(2)}   ${r.minutes.toFixed(1).padStart(5)}     ` +
            `${(r.tierAgree * 100).toFixed(1).padStart(5)}%     ` +
            `${r.alpha.toFixed(3)}      ${r.splitHalf.toFixed(3)}       ${r.sdShare.toFixed(4)}` +
            `      ${r.narrowestTierInSd.toFixed(2)}          ${r.tiersSupported.toFixed(1)}`,
        ),
        "",
        `LIVE POOL (15 real scored items, assigned params): tier-agree ` +
          `${((liveAgreed / livePersons.length) * 100).toFixed(1)}%  alpha ${(liveRel.alpha ?? NaN).toFixed(3)}` +
          `  split-half ${(liveRel.splitHalf ?? NaN).toFixed(3)}  ${delicacyMinutes(liveItems.length).toFixed(1)} min`,
        "",
        "Marginal value of the trials between the shipping length and 42:",
        ...rows
          .filter((r) => r.n >= 15)
          .map((r) => {
            const base = rows.find((x) => x.n === 15)!;
            return (
              `  ${String(r.n).padStart(2)} trials: ${(r.minutes - base.minutes).toFixed(1).padStart(5)} min more` +
              `  ->  tier ${((r.tierAgree - base.tierAgree) * 100).toFixed(1).padStart(5)}pp` +
              `   alpha ${(r.alpha - base.alpha >= 0 ? "+" : "") + (r.alpha - base.alpha).toFixed(3)}`
            );
          }),
      ].join(NL),
    );

    // ---- conclusions, pinned ----

    // Reliability must rise with length; if it does not, the estimator or the
    // bank is broken and every number above describes noise.
    for (let i = 1; i < rows.length; i++) {
      expect(rows[i].alpha, `alpha fell from n=${rows[i - 1].n} to n=${rows[i].n}`).toBeGreaterThan(
        rows[i - 1].alpha - 0.02,
      );
    }
    // Individual precision must improve with length too.
    const first = rows[0];
    const last = rows[rows.length - 1];
    expect(last.sdShare).toBeLessThan(first.sdShare);

    // ---- the findings, pinned ----

    const shipping = rows.find((r) => r.n === 15)!;

    // THE HEADLINE. At the shipping length the six-tier verdict is a coin-flip
    // dressed as a measurement. If a future change makes this pass, the
    // instrument got better and the copy can grow back — that is the moment to
    // revisit, and a failure here is how someone learns of it.
    expect(shipping.tierAgree).toBeLessThan(0.65);

    // THE CAUSE. The narrowest shipped tier is thinner than 2 SD, so the
    // boundary cannot be resolved however confidently the copy states it.
    expect(shipping.narrowestTierInSd).toBeLessThan(2);

    // WHAT THE DATA SUPPORTS: about two bands, against six shipped tiers.
    expect(shipping.tiersSupported).toBeLessThan(3);

    // BOTH ROUTES CONVERGE. Reliability crosses 0.70 and tier width crosses
    // 2 SD in the same region — neither before 30 trials, both by 60. Two
    // unrelated arguments landing together is the load-bearing claim here.
    const alphaCross = rows.find((r) => r.alpha >= 0.7)!;
    const widthCross = rows.find((r) => r.narrowestTierInSd >= 2)!;
    expect(alphaCross.n).toBeGreaterThan(30);
    expect(widthCross.n).toBeGreaterThan(30);
    expect(Math.abs(alphaCross.n - widthCross.n)).toBeLessThanOrEqual(20);

    // And the price of getting there is the session 15 was chosen to avoid.
    expect(delicacyMinutes(42)).toBeGreaterThan(20);
  });
});

/**
 * E6/S8 — HOW MANY TIERS DO 15 TRIALS ACTUALLY SUPPORT?
 *
 * S7 said "about 2.4 bands" using a 2-SD rule of thumb. That rule is mine, not
 * the product's, and picking a tier count from it would be swapping one
 * invented constant for another — the exact move R3 exists to stop.
 *
 * So derive it from a target the product can be held to instead. E6/S6 measured
 * the Prestige verdict at 89.3% agreement; that is the standard the Gym already
 * meets somewhere, so it is a fair bar rather than a flattering one. The
 * question becomes:
 *
 *   What is the LARGEST number of tiers whose printed verdict is right at least
 *   as often as the Prestige verdict is, at the session length we ship?
 *
 * Bands are equal-width in `above` = (nCorrect - n/2)/(n/2), which is the same
 * quantity `delicacyVerdict` already partitions — this changes how finely the
 * range is cut, not what is being cut. Below-chance is its own band in both the
 * current scheme and here, so it is held fixed and not counted.
 */
function bandOf(above: number, k: number): number {
  if (above <= 0) return -1; // at-or-below chance: its own band, unchanged
  return Math.min(k - 1, Math.floor(above * k));
}

describe("E6/S8 — deriving the tier count from a target the product already meets", () => {
  it("finds the finest honest verdict at the shipping length [SIMULATED]", { timeout: 300_000 }, () => {
    const PRESTIGE_AGREEMENT = 0.893; // E6/S6, measured
    const N_TRIALS = 15;
    const rows: Array<{ k: number; agree: number }> = [];

    for (let k = 1; k <= 6; k++) {
      let agreed = 0;
      let total = 0;
      for (let r = 0; r < 6; r++) {
        const seed = 20260821 + r * 7919;
        const items = syntheticDelicacyItems(seed, N_TRIALS);
        const persons = simulatePersons(seed, 900, DEFAULT_PERSON_MODEL);
        const data = simulateDelicacy(seed, items, persons);
        const matrix = delicacyMatrix(SIMULATED, items, data.responses);
        for (const [i, person] of persons.entries()) {
          const nCorrect = matrix.correct[i].filter(Boolean).length;
          const observed = (nCorrect - N_TRIALS / 2) / (N_TRIALS / 2);
          const trueShare =
            items.reduce((a, it) => a + pCorrectSide(it, person.theta), 0) / items.length;
          const truth = 2 * trueShare - 1;
          if (bandOf(observed, k) === bandOf(truth, k)) agreed++;
          total++;
        }
      }
      rows.push({ k, agree: agreed / total });
    }

    const shipped = rows.length; // six named tiers today, for the report line

    // k=1 IS DEGENERATE AND IS NOT AN ANSWER. It asks "is this person above
    // chance at all", and `pCorrectSide` is `0.5 + 0.5*logistic(...)`, so every
    // simulated person is. Measured across 5000 persons: 0.0% have a true
    // `above` at or below zero, minimum 0.083. The comparison has ONE CLASS in
    // it and its 95.9% is a base rate, not an accuracy.
    //
    // This is the THIRD time in E6 that this exact shape produced a
    // decision-grade number. It is excluded here by construction rather than by
    // my remembering, and the assertion below pins the exclusion.
    const DEGENERATE_K = 1;
    const honest = [...rows]
      .reverse()
      .find((r) => r.k > DEGENERATE_K && r.agree >= PRESTIGE_AGREEMENT);

    writeFileSync(
      `${OUT_DIR}/e6-delicacy-tiers.txt`,
      [
        `E6/S8 HOW FINE A VERDICT ${N_TRIALS} TRIALS CARRY [SIMULATED, zero real responses]`,
        `Bar: the Prestige verdict's measured agreement, ${(PRESTIGE_AGREEMENT * 100).toFixed(1)}% (E6/S6).`,
        "Equal-width bands above chance; the below-chance band is unchanged and uncounted.",
        "",
        ...rows.map(
          (r) =>
            `  ${r.k} band${r.k === 1 ? " " : "s"} above chance   agreement ${(r.agree * 100).toFixed(1).padStart(5)}%` +
            (r.k === 1
              ? "   <- DEGENERATE: every simulated person is above chance, so this is a base rate"
              : r.agree >= PRESTIGE_AGREEMENT
                ? "   <- clears the bar"
                : ""),
        ),
        "",
        honest
          ? `FINEST HONEST VERDICT AT ${N_TRIALS} TRIALS: ${honest.k} bands above chance, ` +
            `${(honest.agree * 100).toFixed(1)}% agreement. Shipping today: ${shipped} named tiers.`
          : `NO NON-DEGENERATE BAND COUNT CLEARS ${(PRESTIGE_AGREEMENT * 100).toFixed(1)}% AT ${N_TRIALS} TRIALS.`,
        "",
        "So the answer is not a smaller number of tiers. Even the coarsest real",
        "split — two bands — lands at 70.2%, and the shipped six at 30.5%. At this",
        "length there is no tiered verdict this instrument can print honestly.",
        "",
        "RT-90a already ruled this exact question for the staircase: report the",
        "BAND, never the point, because a point estimate from a noisy measurement",
        "is a claim the measurement cannot support. A tier name IS a point",
        "estimate. The same ruling answers this.",
      ].join(NL),
    );

    // Agreement must fall as the bands get finer — more boundaries, more ways
    // to land on the wrong side of one. A curve that rose would mean the
    // measurement is wrong, which is how three earlier bugs in this epic
    // announced themselves.
    for (let i = 1; i < rows.length; i++) {
      expect(rows[i].agree, `agreement rose from k=${rows[i - 1].k} to k=${rows[i].k}`).toBeLessThanOrEqual(
        rows[i - 1].agree + 0.01,
      );
    }
    // The shipped resolution must NOT clear the bar — that is the finding.
    expect(rows[rows.length - 1].agree).toBeLessThan(PRESTIGE_AGREEMENT);
    // Nor must ANY non-degenerate count. If a future pool or length makes one
    // clear it, tiering becomes defensible again and this test failing is how
    // someone finds out.
    expect(honest, "a non-degenerate tier count now clears the bar").toBeUndefined();
    // And the degenerate row must stay recognisably degenerate: it can only
    // score high because it has one class.
    expect(rows[0].agree).toBeGreaterThan(rows[1].agree + 0.2);
  });
});
