import type { Metadata } from "next";
import Link from "next/link";
import SourceBadge from "@/components/lab/SourceBadge";
import { delicacyMatrix, estimateItems, estimateReliability, gradeItems, type ItemGrade } from "@/analytics/estimate";
import { fitIrt, irtDiscriminationById, irtProbability } from "@/analytics/irt";
import { assignDelicacyParams, simulateDelicacy, simulatePersons } from "@/analytics/simulate";
import { DELICACY_TRIALS } from "@/content/delicacy/items";
import delicacyManifest from "@/content/delicacy/manifest.json";
import { metric } from "@/content/lab/metrics";

/**
 * Instrument-health panel (artifact pivot §4).
 *
 * TWO LAYERS, SHOWN SEPARATELY AND ON PURPOSE:
 *  - Layer A is REAL. Every number in the first table was measured off the
 *    shipped audio by `clip-pipeline validate` and lives in the manifest. It
 *    carries no SIMULATED badge because nothing about it is simulated.
 *  - Layer B is SIMULATED, and loudly. The instrument has never been fielded,
 *    so every difficulty and discrimination figure below comes from responses
 *    generated by a known model. They demonstrate that the pipeline works; they
 *    say nothing about any real listener, and the page says so where a reader
 *    cannot miss it.
 *
 * Mixing those two on one surface without distinguishing them would be the
 * single most misleading thing this project could do, which is why they get
 * separate sections, separate badges, and separate framing rather than one
 * tidy combined table.
 */

export const metadata: Metadata = {
  title: "Instrument health — The Lab",
  description:
    "Item-level health for the Delicacy Trials: measured manipulation magnitudes from the shipped audio, and the psychometric pipeline demonstrated on simulated responses.",
  alternates: { canonical: "/lab/instrument-health" },
  openGraph: {
    title: "Instrument health — The Lab",
    description: "Every item, measured: manipulation magnitude, difficulty, discrimination, and the verdict that follows.",
    images: [{ url: "/opengraph-image", width: 1200, height: 630 }],
  },
};

const GOLD = "hsl(42 80% 62%)";
const SIM_PERSONS = 600;
const SIM_SEED = 4242;

type LayerA = {
  lsdDb: number;
  anchorRatio: number;
  anchorTransparentLsdDb: number;
  driftIqrMs: number;
  gatedOn: string;
  verdict: string;
};

const num = (x: number | null | undefined, dp = 2) => (x === null || x === undefined ? "—" : x.toFixed(dp));

const VERDICT_STYLE: Record<string, string> = {
  ACCEPT: "text-emerald-300/90",
  PENDING: "text-muted",
  TOO_EASY: "text-amber-300/90",
  TOO_HARD: "text-amber-300/90",
  RETIRE: "text-rose-300/90",
};

/** Item characteristic curve — the shape a 2PL item actually has. */
function IccChart({ items }: { items: { id: string; a: number; b: number }[] }) {
  const W = 320;
  const H = 150;
  const PAD = 26;
  const x = (t: number) => PAD + ((t + 3) / 6) * (W - 2 * PAD);
  const y = (p: number) => H - PAD - ((p - 0.5) / 0.5) * (H - 2 * PAD);
  const thetas = Array.from({ length: 61 }, (_, i) => -3 + i * 0.1);

  return (
    <svg
      viewBox={`0 0 ${W} ${H}`}
      className="block w-full"
      role="img"
      aria-label={`Item characteristic curves for ${items.length} delicacy trials. Each curve shows the probability of a correct answer rising from the fifty percent chance floor as listener ability increases.`}
    >
      <rect x={PAD} y={PAD} width={W - 2 * PAD} height={H - 2 * PAD} fill="rgba(255,255,255,0.02)" stroke="rgba(255,255,255,0.12)" strokeWidth={0.75} />
      {/* The chance floor is the reference line that matters most here. */}
      <line x1={PAD} y1={y(0.5)} x2={W - PAD} y2={y(0.5)} stroke="rgba(255,255,255,0.35)" strokeWidth={0.75} strokeDasharray="3 3" />
      <text x={W - PAD - 2} y={y(0.5) - 4} textAnchor="end" fill="rgba(255,255,255,0.45)" fontSize={7} fontFamily="monospace">
        chance 50%
      </text>
      {items.map((item) => (
        <polyline
          key={item.id}
          fill="none"
          stroke={GOLD}
          strokeOpacity={0.4}
          strokeWidth={1}
          points={thetas.map((t) => `${x(t)},${y(irtProbability(item, t))}`).join(" ")}
        />
      ))}
      {[-3, 0, 3].map((t) => (
        <text key={t} x={x(t)} y={H - PAD + 10} textAnchor="middle" fill="rgba(255,255,255,0.45)" fontSize={7} fontFamily="monospace">
          {t > 0 ? `+${t}` : t}
        </text>
      ))}
      <text x={W / 2} y={H - 3} textAnchor="middle" fill="rgba(255,255,255,0.55)" fontSize={7.5} fontFamily="monospace">
        listener ability θ (logits)
      </text>
      <text x={9} y={H / 2} textAnchor="middle" fill="rgba(255,255,255,0.55)" fontSize={7.5} fontFamily="monospace" transform={`rotate(-90 9 ${H / 2})`}>
        P(correct)
      </text>
    </svg>
  );
}

export default function InstrumentHealthPanel() {
  // ---- Layer A: measured off the shipped audio. Not simulated.
  const manifestPairs = (delicacyManifest as { pairs: ({ id: string; layerA?: LayerA } & Record<string, unknown>)[] }).pairs;
  const layerA = new Map(manifestPairs.filter((p) => p.layerA).map((p) => [p.id, p.layerA as LayerA]));
  const anchors = manifestPairs.map((p) => p.layerA?.anchorTransparentLsdDb).filter((x): x is number => typeof x === "number");

  // ---- Layer B: the pipeline, demonstrated on responses from a known model.
  const items = assignDelicacyParams(DELICACY_TRIALS);
  const persons = simulatePersons(SIM_SEED, SIM_PERSONS);
  const matrix = delicacyMatrix("SIMULATED", items, simulateDelicacy(SIM_SEED, items, persons).responses);
  const stats = estimateItems(matrix);
  const reliability = estimateReliability(matrix);
  const irt = fitIrt(matrix);
  const grades = gradeItems(stats, reliability.alpha, irtDiscriminationById(irt));
  const gradeById = new Map(grades.grades.map((g: ItemGrade) => [g.id, g]));
  const irtById = new Map(irt.items.map((i) => [i.id, i]));

  return (
    <div>
      <p className="mt-10 text-[0.65rem] font-bold tracking-[0.3em] text-muted">
        <Link href="/lab" className="transition hover:text-white">
          THE LAB
        </Link>{" "}
        / INSTRUMENT HEALTH
      </p>
      <h1 className="mt-2 max-w-3xl font-display text-4xl font-semibold leading-[1.05] tracking-tight sm:text-5xl">
        Every item, and what is known about it.
      </h1>
      <p className="mt-5 max-w-2xl text-[15px] leading-relaxed text-neutral-300">
        An instrument is only as good as its worst item, and most products never show you either. This
        page shows all {DELICACY_TRIALS.length}. It is split in two because the two halves have
        completely different standing: what has been <em>measured off the audio</em>, and what the
        analysis pipeline <em>would</em> say once people have actually sat the test.
      </p>

      {/* ------------------------------------------------------- LAYER A (real) */}
      <section className="mt-14">
        <div className="flex flex-wrap items-center gap-x-3 gap-y-2">
          <h2 className="font-display text-2xl font-semibold tracking-tight">Layer A — manipulation magnitude</h2>
          <SourceBadge source="REAL" />
        </div>
        <p className="mt-2 max-w-2xl text-sm text-muted">
          Measured off the shipped audio files by the render pipeline. Each item&rsquo;s manipulation is
          compared against a 320 kbps round-trip of <em>its own source</em>{" "}
          — a change that is real, measurable, and inaudible. A ratio of 4× means &ldquo;four times the size of something nobody
          can hear&rdquo;, which is not the same as &ldquo;four times as obvious&rdquo;.
        </p>
        <p className="mt-3 max-w-2xl text-xs leading-relaxed text-muted">
          Anchors across the pool span {num(Math.min(...anchors), 2)}–{num(Math.max(...anchors), 2)} dB,
          a {num(Math.max(...anchors) / Math.min(...anchors), 1)}× spread: dense material loses more to a
          transparent codec, so it needs a larger absolute manipulation to clear the same ratio. Timing
          items are gated on measured drift instead, because a time-warped pair falls out of step and the
          spectral distance stops describing the manipulation.
        </p>

        <div className="mt-5 overflow-x-auto rounded-2xl border border-white/10 bg-white/[0.03] p-5">
          <table className="w-full min-w-[46rem] text-left text-xs">
            <thead>
              <tr className="font-mono text-[0.6rem] tracking-[0.15em] text-muted">
                <th className="pb-2 pr-4 font-normal">ITEM</th>
                <th className="pb-2 pr-4 font-normal">FAMILY</th>
                <th className="pb-2 pr-4 font-normal">RUNG</th>
                <th className="pb-2 pr-4 font-normal">LSD dB</th>
                <th className="pb-2 pr-4 font-normal">ANCHOR</th>
                <th className="pb-2 pr-4 font-normal">×ANCHOR</th>
                <th className="pb-2 pr-4 font-normal">DRIFT IQR</th>
                <th className="pb-2 pr-4 font-normal">GATED ON</th>
                <th className="pb-2 font-normal">VERDICT</th>
              </tr>
            </thead>
            <tbody>
              {DELICACY_TRIALS.map((t) => {
                const a = layerA.get(t.id);
                const temporal = a?.gatedOn === "temporal-drift";
                return (
                  <tr key={t.id} className="border-t border-white/10">
                    <td className="py-2 pr-4 font-mono text-neutral-200">{t.id}</td>
                    <td className="py-2 pr-4 text-neutral-300">{t.family}</td>
                    <td className="py-2 pr-4 font-mono text-neutral-400">{t.magnitude}</td>
                    <td className="py-2 pr-4 font-mono text-neutral-200">{num(a?.lsdDb)}</td>
                    <td className="py-2 pr-4 font-mono text-neutral-400">{num(a?.anchorTransparentLsdDb)}</td>
                    <td className="py-2 pr-4 font-mono" style={{ color: temporal ? undefined : GOLD }}>
                      {temporal ? <span className="text-muted">n/a</span> : `${num(a?.anchorRatio, 1)}×`}
                    </td>
                    <td className="py-2 pr-4 font-mono" style={{ color: temporal ? GOLD : undefined }}>
                      <span className={temporal ? "" : "text-neutral-400"}>{a ? `${a.driftIqrMs} ms` : "—"}</span>
                    </td>
                    <td className="py-2 pr-4 font-mono text-[0.7rem] text-neutral-400">{a?.gatedOn ?? "—"}</td>
                    <td className="py-2 font-mono text-emerald-300/90">{a?.verdict ?? "—"}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </section>

      {/* ------------------------------------------------- LAYER B (simulated) */}
      <section className="mt-16">
        <div className="flex flex-wrap items-center gap-x-3 gap-y-2">
          <h2 className="font-display text-2xl font-semibold tracking-tight">Layer B — difficulty & discrimination</h2>
          <SourceBadge source="SIMULATED" />
        </div>

        <div className="mt-4 rounded-2xl border border-dashed border-white/20 bg-white/[0.02] p-5">
          <p className="text-sm leading-relaxed text-neutral-300">
            <strong className="font-semibold text-white">Nobody has taken this test.</strong> Every number
            in this section comes from {SIM_PERSONS}{" "}
            simulated respondents generated from a known
            ability model, and every item&rsquo;s true parameters were assigned by us rather than
            measured from anyone. It demonstrates that the estimation pipeline runs and that the
            auto-flag reaches sensible verdicts — it is <em>not</em> evidence about these items or about
            any listener. When real responses arrive they flow through this identical code and the only
            thing that changes is the badge above.
          </p>
        </div>

        <div className="mt-6 grid gap-6 lg:grid-cols-[320px_1fr]">
          <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4">
            <IccChart items={irt.items.filter((i) => !i.atBound)} />
            <p className="mt-2 text-center font-mono text-[0.6rem] tracking-[0.15em] text-muted">
              ITEM CHARACTERISTIC CURVES
            </p>
            <p className="mt-3 text-xs leading-relaxed text-muted">
              Each curve is one item. They start at the 50% chance floor — a two-alternative task cannot
              do worse than a coin — and rise with listener ability. A steeper curve separates listeners
              more sharply; a curve shifted right is a harder item.
            </p>
          </div>

          <div className="overflow-x-auto rounded-2xl border border-white/10 bg-white/[0.03] p-5">
            <table className="w-full min-w-[34rem] text-left text-xs">
              <thead>
                <tr className="font-mono text-[0.6rem] tracking-[0.15em] text-muted">
                  <th className="pb-2 pr-4 font-normal">ITEM</th>
                  <th className="pb-2 pr-4 font-normal">p</th>
                  <th className="pb-2 pr-4 font-normal">±SE</th>
                  <th className="pb-2 pr-4 font-normal">IRT a</th>
                  <th className="pb-2 pr-4 font-normal">IRT b</th>
                  <th className="pb-2 pr-4 font-normal">BASIS</th>
                  <th className="pb-2 font-normal">VERDICT</th>
                </tr>
              </thead>
              <tbody>
                {DELICACY_TRIALS.map((t) => {
                  const g = gradeById.get(t.id);
                  const i = irtById.get(t.id);
                  return (
                    <tr key={t.id} className="border-t border-white/10">
                      <td className="py-2 pr-4 font-mono text-neutral-200">{t.id}</td>
                      <td className="py-2 pr-4 font-mono text-neutral-200">{num(g?.pValue)}</td>
                      <td className="py-2 pr-4 font-mono text-neutral-400">{num(g?.pStandardError)}</td>
                      <td className="py-2 pr-4 font-mono text-neutral-200">
                        {i?.atBound ? <span className="text-rose-300/80">unlocated</span> : num(i?.a)}
                      </td>
                      <td className="py-2 pr-4 font-mono text-neutral-400">{i?.atBound ? "—" : num(i?.b)}</td>
                      <td className="py-2 pr-4 font-mono text-[0.7rem] text-neutral-400">
                        {g?.discriminationBasis.metric ?? "—"}
                      </td>
                      <td className={`py-2 font-mono ${VERDICT_STYLE[g?.verdict ?? "PENDING"]}`}>{g?.verdict ?? "—"}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

        <div className="mt-6 flex flex-col gap-3">
          <Stat label="Reliability (Cronbach's α)" value={num(reliability.alpha, 3)} note={metric("alpha").caveat!} />
          <Stat
            label="Split-half (Spearman-Brown)"
            value={num(reliability.splitHalf, 3)}
            note={metric("split_half").caveat!}
          />
          <Stat
            label="Auto-flag summary"
            value={Object.entries(grades.summary)
              .filter(([, v]) => v > 0)
              .map(([k, v]) => `${k} ${v}`)
              .join(" · ")}
            note="Verdicts follow the acceptance band: difficulty is judged first because an out-of-band item has a cheap fix — move it a rung on the strength ladder — while retirement is terminal."
          />
          {grades.warning && <Stat label="Gate warning" value="see note" note={grades.warning} />}
          {irt.warning && <Stat label="IRT fit warning" value="see note" note={irt.warning} />}
        </div>
      </section>

      <p className="mt-12 max-w-2xl text-xs leading-relaxed text-muted">
        Layer A is read from <code className="font-mono">src/content/delicacy/manifest.json</code>, written
        by <code className="font-mono">clip-pipeline validate</code>. Layer B is computed at build time from{" "}
        {SIM_PERSONS} simulated respondents (seed {SIM_SEED}) using the same estimators the test suite
        runs, so this page and{" "}
        <code className="font-mono">src/analytics/*.test.ts</code> cannot disagree.
      </p>
    </div>
  );
}

function Stat({ label, value, note }: { label: string; value: string; note: string }) {
  return (
    <article className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
      <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1">
        <h3 className="font-display text-lg font-semibold">{label}</h3>
        <code className="font-mono text-sm" style={{ color: GOLD }}>
          {value}
        </code>
      </div>
      <p className="mt-2 text-xs leading-relaxed text-muted">{note}</p>
    </article>
  );
}
